### ISSUE TITLE
checkpoints are missing

### ISSUE THREAD

**Issue by kingaza** [woxuankai/SpatialAlignmentNetwork#1]
hello,

So nice of you to share your work.
Could you also provide the checkpoints in T1_4xRandomT2_GANOnly and T1_4xRandomT2_GANOnly as mentioned in README.md?

thx a lot.

Best Regards,
kingaza

**Comment by woxuankai** [comment]
Hey there, 

My apology for the wrong order of procedures.

Just run the code in `GAN only for spatial alignment network (GAN)` section first and you will get the corresponding checkpoints.

Baseline model mentioned in the readme.md uses checkpoints from` T1_4xRandomT2_GANOnly` just to insure the same Random mask will be used.

Best,
Kai

**Comment by kingaza** [comment]
thx, it works.
