### ISSUE TITLE
t1_t2_paired_6875_{train,val,test}.csv

### ISSUE THREAD

**Issue by chke097** [woxuankai/SpatialAlignmentNetwork#2]
Hello, according to the CSV file you gave me, I have some problems in selecting the T1T2 data pair of the training set. 
       For example, the training data pair you gave me has folder 794098270851, but actually the DICOM format of folder 794098270851 has not been converted into NII files of T1 and T2. Therefore, NII cannot be changed into H5 file. 
       May I ask how to solve this error? Looking forward to your reply, thank you!

**Comment by chke097** [comment]
Hello, I met this problem when I was converting NII from DCM:

Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90'

 Could you tell me how to solve it? Thank you

**Comment by woxuankai** [comment]
> Hello, I met this problem when I was converting NII from DCM:
> 
> Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90'
> 
> Could you tell me how to solve it? Thank you

Thank you for your interest.
The `dcm2niix` package provided by Debian 11 works well for me.
Will you please try solutions in [this page](https://neurostars.org/t/unsupported-transfer-syntex-when-using-dcm2niix/6089/3) ?

**Comment by chke097** [comment]
Hello, could you please tell me the version of dcm2niix package you are using？Thank you

**Comment by woxuankai** [comment]
Hi there, more details of the dcm2niix package are available at https://packages.debian.org/bullseye/dcm2niix

**Comment by rederyang** [comment]
@chke097 Maybe this issue can help you. https://github.com/rordenlab/dcm2niix/issues/630

**Comment by chke097** [comment]
Thank you! It’s working.

**Comment by rederyang** [comment]
@chke097 😃
