### ISSUE TITLE
The problem of GPU

### ISSUE THREAD

**Issue by chke097** [woxuankai/SpatialAlignmentNetwork#3]
Hello, I use NVIDIA GeForce GTX 1080 Ti to run your first data set, and found that it takes a very long time, showing that it took 100 days. Could you tell me the type of gpu you used and how long it takes you? Thank you!

The parameter 'range' is deprecated since 0.12 and will be removed in 0.14. Please use 'value_range' instead.
  "The parameter 'range' is deprecated since 0.12 and will be removed in 0.14. "
epoch:   0%|

**Comment by chke097** [comment]
The parameter 'range' is deprecated since 0.12 and will be removed in 0.14. Please use 'value_range' instead.
  "The parameter 'range' is deprecated since 0.12 and will be removed in 0.14. "
epoch:   0%|                                                                                              | 3/20000 [21:36<2403:09:38, 432.63s/it]

**Comment by woxuankai** [comment]
> Could you tell me the type of gpu you used and how long it takes you

less than one week with a RTX3090 (typically within 3 days)

> showing that it took 100 days

the training process will exit if convergence is met

**Comment by rederyang** [comment]
> Hello, I use NVIDIA GeForce GTX 1080 Ti to run your first data set, and found that it takes a very long time, showing that it took 100 days. Could you tell me the type of gpu you used and how long it takes you? Thank you!
> 
> The parameter 'range' is deprecated since 0.12 and will be removed in 0.14. Please use 'value_range' instead. "The parameter 'range' is deprecated since 0.12 and will be removed in 0.14. " epoch: 0%|

It took me around a week to finish the experiments with an RTX 3060.
