### ISSUE TITLE
about Prerequisites

### ISSUE THREAD

**Issue by Markszly** [woxuankai/SpatialAlignmentNetwork#4]
作者您好，请问能否告知您的实验环境和相关配置呢？万分感谢

**Comment by woxuankai** [comment]
Hi there, scripts provided in this repository were tested with python3.9 (provided by Debian Bullseye) and PyTorch 1.8 (installed via pip).

**Comment by Markszly** [comment]
> Hi there, scripts provided in this repository were tested with python3.9 (provided by Debian Bullseye) and PyTorch 1.8 (installed via pip).

Thank you so much！
