### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by wujm7** [woxuankai/SpatialAlignmentNetwork#5]
作者您好，冒昧打扰您了，我想问一下，你在文档中所说的解压数据文件“Unzip fastMRI brain DICOM to fastMRI_brain_DICOM folder.”的那个数据在哪里呢，没有看见压缩包呀？

**Comment by woxuankai** [comment]
Visit https://fastmri.med.nyu.edu/, download links will be sent to your mailbox after your submitting the _NYU Langone Health fastMRI Dataset Sharing Agreement_.

**Comment by wujm7** [comment]
作者您好 能不能再打扰一下 我想问一下 我运行那个commands_train_test出现“/LOG/4xEquispaced/ckpt/best.pt/*': No such file or directory” 想问一下这个文件夹里存的应该是什么文件啊？

**Comment by woxuankai** [comment]
This directory is supposed to contain saved checkpoints.
Have you finished the training processes in https://github.com/woxuankai/SpatialAlignmentNetwork/blob/main/commands_train_test.sh#L32,
https://github.com/woxuankai/SpatialAlignmentNetwork/blob/main/commands_train_test.sh#L34,
https://github.com/woxuankai/SpatialAlignmentNetwork/blob/main/commands_train_test.sh#L36,
and https://github.com/woxuankai/SpatialAlignmentNetwork/blob/main/commands_train_test.sh#L38?
